name: Check for Broken Links

permissions: read-all

on:
  workflow_run:
    workflows: ["Deployment"]
    types: [completed]
  schedule:
    - cron: "28 2 * * *"
  workflow_dispatch:

jobs:
  check-links:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check for broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: "https://unwcsclub.dev"
          cmd_params: >-
            --exclude '.*coolbibleverses\.cool.*'
            --exclude '.*linkedin\.com.*'
            --buffer-size 8000
            --timeout 20
            --color=always
