name: Deployment

on:
  push:
    branches:
      - main

permissions: read-all

concurrency: production

jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Get Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Dependencies
        run: npm ci

      - name: Install Netlify CLI
        run: npm i -g netlify-cli@20

      - name: Build
        run: "npm run build:production"

      - name: Install Host Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WEBSERVER_SSH_HOST }} ${{ secrets.WEBSERVER_HOST_KEY }}" >> ~/.ssh/known_hosts

      - run: .github/scripts/deploy.bash
        env:
          SSH_PRIVATE_KEY: |
            ${{ secrets.DEPLOYMENT_KEY }}
          WEBSERVER_SSH_HOST: ${{ secrets.WEBSERVER_SSH_HOST }}
          WEBSERVER_SSH_PORT: ${{ secrets.WEBSERVER_SSH_PORT }}
          WEBSERVER_SSH_USER: ${{ secrets.WEBSERVER_SSH_USER }}

      - name: Deploy CDN Assets
        run: netlify deploy --dir=cdn-build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}

      - name: Check website
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: "https://unwcsclub.dev"
          cmd_params: >-
            -b 8000
            --one-page-only
            --color always
            --verbose
            --include "https://cdn.unwcsclub.dev/.*"
